### ISSUE TITLE
[Enhancement] Update android pom to use newer android-maven-plugin (3.8+)

### ISSUE THREAD

**Issue by ouchadam** [novoda/public-mvn-repo#4]
Finally migrates to the latest version of maven! (3.1.1) + [other good stuff](https://code.google.com/p/maven-android-plugin/wiki/Changelog)

[This line](https://github.com/novoda/public-mvn-repo/blob/master/releases/com/novoda/android/2.1.1/android-2.1.1.pom#L19)

**Comment by blundell** [comment]
I thought maven 3.1 has issues with something that I can't recall? I'm still rocking maven 3.0.3

**Comment by ouchadam** [comment]
yeah the android-maven-plugin! which is now fixed as of 3.8. It's not super important but it would be nice.

**Comment by mr-archano** [comment]
@blundell I guess you meant this http://stackoverflow.com/questions/8826881/maven-install-on-mac-os-x#comment29039353_17481557

**Comment by juankysoriano** [comment]
Closing as the repository is no longer under maintenance and it is about to be archived
